---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix, auto]
    -   id: pretty-format-json
        args: [--autofix, --indent, '4']
-   repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
    -   id: yamlfix
        args: [--config-file, .yamlfix.toml]
