---
services:
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        restart: unless-stopped
        cap_add:
        -   NET_ADMIN
        devices:
        -   /dev/net/tun:/dev/net/tun
        environment:
        -   TZ=${SERVER_TIME_ZONE}
        -   VPN_SERVICE_PROVIDER=mullvad
        -   VPN_TYPE=wireguard
        -   WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
        -   WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
        labels:
        # qBitTorrent
        -   traefik.enable=true
        -   traefik.http.routers.qbit.service=qbit
        -   traefik.http.routers.qbit.entrypoints=private
        -   traefik.http.routers.qbit.rule=Host(`qbit.${DOMAIN_NAME}`)
        -   traefik.http.services.qbit.loadbalancer.server.port=8080
        # Prowlarr
        -   traefik.http.routers.prowlarr.service=prowlarr
        -   traefik.http.routers.prowlarr.entrypoints=private
        -   traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN_NAME}`)
        -   traefik.http.services.prowlarr.loadbalancer.server.port=9696
        # Radarr
        -   traefik.http.routers.radarr.service=radarr
        -   traefik.http.routers.radarr.entrypoints=private
        -   traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)
        -   traefik.http.services.radarr.loadbalancer.server.port=7878
        # Sonarr
        -   traefik.http.routers.sonarr.service=sonarr
        -   traefik.http.routers.sonarr.entrypoints=private
        -   traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_NAME}`)
        -   traefik.http.services.sonarr.loadbalancer.server.port=8989
    qbittorrent:
        image: linuxserver/qbittorrent:5.1.4-libtorrentv1
        container_name: qbittorrent
        restart: unless-stopped
        environment:
        -   PUID=1000
        -   PGID=1000
        -   TZ=${SERVER_TIME_ZONE}
        -   WEBUI_PORT=8080
        -   TORRENTING_PORT=6881
        volumes:
        -   ${SERVER_CONFIG_PATH}/qbittorrent:/config
        -   ${NAS_MEDIA_PATH}/torrents:/media/torrents
        network_mode: service:gluetun
        depends_on:
            gluetun:
                condition: service_healthy
    prowlarr:
        image: linuxserver/prowlarr:2.3.5-nightly
        container_name: prowlarr
        restart: unless-stopped
        environment:
        -   PUID=1000
        -   PGID=1000
        -   TZ=${SERVER_TIME_ZONE}
        volumes:
        -   ${SERVER_CONFIG_PATH}/prowlarr:/config
        network_mode: service:gluetun
        depends_on:
            gluetun:
                condition: service_healthy
    radarr:
        image: linuxserver/radarr:6.1.2-develop
        container_name: radarr
        restart: unless-stopped
        environment:
        -   PUID=1000
        -   PGID=1000
        -   TZ=${SERVER_TIME_ZONE}
        volumes:
        -   ${SERVER_CONFIG_PATH}/radarr:/config
        -   ${NAS_MEDIA_PATH}:/media
        network_mode: service:gluetun
        depends_on:
            gluetun:
                condition: service_healthy
    sonarr:
        image: linuxserver/sonarr:4.0.17-develop
        container_name: sonarr
        restart: unless-stopped
        environment:
        -   PUID=1000
        -   PGID=1000
        -   TZ=${SERVER_TIME_ZONE}
        volumes:
        -   ${SERVER_CONFIG_PATH}/sonarr:/config
        -   ${NAS_MEDIA_PATH}:/media
        network_mode: service:gluetun
        depends_on:
            gluetun:
                condition: service_healthy
networks:
    default:
        name: ${OVERLAY_NETWORK}
        external: true
