---
services:
    headscale:
        image: headscale/headscale:v0.25.1
        container_name: headscale
        restart: unless-stopped
        command: serve
        volumes:
        -   ${SERVER_CONFIG_PATH}/headscale:/etc/headscale
        -   ${SERVER_DATA_PATH}/headscale:/var/lib/headscale
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.headscale.entrypoints=public
        -   traefik.http.routers.headscale.rule=Host(`headscale.${DOMAIN_NAME}`)
        -   traefik.http.services.headscale.loadbalancer.server.port=8080
    headplane:
        image: ghcr.io/tale/headplane:0.5.10
        container_name: headplane
        restart: unless-stopped
        volumes:
        -   ${SERVER_CONFIG_PATH}/headplane/config.yaml:/etc/headplane/config.yaml
        -   ${SERVER_CONFIG_PATH}/headscale/config.yaml:/etc/headscale/config.yaml
        -   ${SERVER_DATA_PATH}/headplane:/var/lib/headplane
        -   /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.headplane.entrypoints=private
        -   traefik.http.routers.headplane.rule=Host(`headplane.${DOMAIN_NAME}`)
        -   traefik.http.services.headplane.loadbalancer.server.port=3000
networks:
    default:
        name: ${OVERLAY_NETWORK}
        external: true
