---
services:
    jellyfin:
        image: jellyfin/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        devices:
        -   /dev/dri/renderD128:/dev/dri/renderD128
        environment:
        -   PUID=1000
        -   PGID=1000
        -   TZ=${SERVER_TIME_ZONE}
        volumes:
        -   ${SERVER_CONFIG_PATH}/jellyfin:/config
        -   ${SERVER_DATA_PATH}/jellyfin/config_data:/config/data
        -   ${SERVER_DATA_PATH}/jellyfin/data:/data/jellyfin
        -   ${SERVER_CACHE_PATH}/jellyfin/cache:/cache
        -   ${SERVER_CACHE_PATH}/jellyfin/metadata:/data/jellyfin/metadata
        -   ${NAS_MEDIA_PATH}/main:/data/nas_main:ro
        -   ${NAS_MEDIA_PATH}/movies:/data/nas_movies
        -   ${NAS_MEDIA_PATH}/shows:/data/nas_shows
        -   ${NAS_MEDIA_PATH}/misc:/data/nas_misc
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.jellyfin.entrypoints=private
        -   traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)
        -   traefik.http.services.jellyfin.loadbalancer.server.port=8096
    jellyseerr:
        image: fallenbagel/jellyseerr
        container_name: jellyseerr
        restart: unless-stopped
        environment:
        -   TZ=${SERVER_TIME_ZONE}
        volumes:
        -   ${SERVER_CONFIG_PATH}/jellyseer:/app/config
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.jellyseer.entrypoints=private
        -   traefik.http.routers.jellyseer.rule=Host(`jellyseer.${DOMAIN_NAME}`)
        -   traefik.http.services.jellyseer.loadbalancer.server.port=5055
networks:
    default:
        name: ${OVERLAY_NETWORK}
        external: true
