---
services:
  kavita:
    image: linuxserver/kavita
    container_name: kavita
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${SERVER_TIME_ZONE}"
    volumes:
      - "${SERVER_CONFIG_PATH}/kavita:/config"
      - "${SERVER_DATA_PATH}/kavita:/data"

networks:
  default:
    name: overlay
    external: true
