---
services:
    navidrome:
        image: deluan/navidrome:develop
        container_name: navidrome
        restart: unless-stopped
        volumes:
        -   ${SERVER_DATA_PATH}/navidrome/data:/data
        -   ${NAS_MEDIA_PATH}/music:/music:ro
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.navidrome.entrypoints=public
        -   traefik.http.routers.navidrome.rule=Host(`navidrome.${DOMAIN_NAME}`)
        -   traefik.http.services.navidrome.loadbalancer.server.port=4533
networks:
    default:
        name: ${OVERLAY_NETWORK}
        external: true
