---
services:
  couchdb:
    image: couchdb
    container_name: obsidian_couchdb
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - "COUCHDB_USER=${OBSIDIAN_COUCHDB_USERNAME}"
      - "COUCHDB_PASSWORD=${OBSIDIAN_COUCHDB_PASSWORD}"
    volumes:
      - "${SERVER_DATA_PATH}/obsidian:/opt/couchdb/data"
      - "${SERVER_CONFIG_PATH}/obsidian/local.ini:/opt/couchdb/etc/local.ini"

networks:
  default:
    name: overlay
    external: true
