---
services:
    obsidian_couchdb:
        image: couchdb
        container_name: obsidian_couchdb
        restart: unless-stopped
        user: 1000:1000
        environment:
        -   COUCHDB_USER=${COUCHDB_USERNAME}
        -   COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        volumes:
        -   ${SERVER_DATA_PATH}/obsidian:/opt/couchdb/data
        -   ${SERVER_CONFIG_PATH}/obsidian/local.ini:/opt/couchdb/etc/local.ini
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.obsidian_couchdb.tls=true
        -   traefik.http.routers.obsidian_couchdb.tls.certresolver=${CERT_RES_DNS}
        -   traefik.http.routers.obsidian_couchdb.entrypoints=${HTTPS_ENTRY}
        -   traefik.http.routers.obsidian_couchdb.rule=Host(`obsidian.${DOMAIN_NAME}`)
        -   traefik.http.services.obsidian_couchdb.loadbalancer.server.port=5984
networks:
    default:
        name: ${OVERLAY_NETWORK}
        external: true
