---
services:
    traefik:
        image: traefik
        container_name: traefik
        restart: unless-stopped
        ports:
        -   80:80
        -   443:443
        -   9009:8080
        environment:
        -   CF_API_EMAIL=${CLOUDFLARE_API_EMAIL}
        -   CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
        volumes:
        -   ${SERVER_CONFIG_PATH}/traefik:/etc/traefik
        -   ${SERVER_DATA_PATH}/traefik/ssl-certs:/ssl-certs
        -   /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.traefik.entrypoints=private
        -   traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
        -   traefik.http.routers.traefik.service=api@internal
networks:
    default:
        name: ${OVERLAY_NETWORK}
        external: true
