---
services:
    wireguard:
        container_name: wireguard
        image: ghcr.io/wg-easy/wg-easy
        restart: unless-stopped
        cap_add:
        -   NET_ADMIN
        -   SYS_MODULE
        sysctls:
        -   net.ipv4.ip_forward=1
        -   net.ipv4.conf.all.src_valid_mark=1
        ports:
        -   51820:51820/udp
        -   9003:51821
        environment:
        -   WG_HOST=${DOMAIN_NAME}
        -   PASSWORD=${WEB_PASSWORD}
        -   WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
        -   WG_DEFAULT_DNS=${DNS_SERVER}
        -   UI_TRAFFIC_STATS=true
        -   UI_CHART_TYPE=2
        volumes:
        -   ${SERVER_CONFIG_PATH}/wireguard:/etc/wireguard
        labels:
        -   traefik.enable=true
        -   traefik.http.routers.wireguard.tls=true
        -   traefik.http.routers.wireguard.tls.certresolver=${CERT_RES_DNS}
        -   traefik.http.routers.wireguard.entrypoints=${HTTPS_ENTRY}
        -   traefik.http.routers.wireguard.rule=Host(`wireguard.${DOMAIN_NAME}`)
        -   traefik.http.routers.wireguard.middlewares=${MIDDLEWARE_PRIVATE}
        -   traefik.http.services.wireguard.loadbalancer.server.port=51821
networks:
    default:
        name: ${OVERLAY_NETWORK}
        external: true
